services:
  mongodb:
    build: ./mongodb
    image: vamsi562/mongodb:v1
    container_name: mongo
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data

  mysql:
    build: ./mysql
    image: vamsi562/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  catalogue:
    build: ./catalogue
    image: vamsi562/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build: ./user
    image: vamsi562/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    build: ./cart
    image: vamsi562/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping:
    build: ./shipping
    image: vamsi562/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    build: ./payment
    image: vamsi562/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - user
      - cart

  frontend:
    build: ./frontend
    image: vamsi562/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

networks:
  roboshop:

volumes:
  mongodb:
  mysql:
  redis:
  rabbitmq:
